CMS ARS 3.1 Low Overlay
CMSgov/cms-ars-3.1-low-microsoft-sql-server-2017-cis-overlay pull request #1
Opened 2022-05-04 14:52 UTC by karikarshivani

2022-05-04 14:54 UTC, karikarshivani commented on inspec.yml
>      description: 'The username MSSQL DB Server'
I'll update the branch name in the `depends.url` when the PR for the baseline has been approved and merged. Thanks!

2022-06-09 20:12 UTC, ejaronne requested changes
microsoft-sql-server-2017-cis-1.2 relates to SI-10 (only for Mod/High) and SC-32 (non-mandatory). In planning in CFACTS, CMS ARS 3.1 non-mandatory controls are optional for ISSOs to adopt, and therefore may be something they still wish to include in their application's control set. Therefore, we don't exclude (make not applicable) a requirement based on non-mandatory NIST controls.

2022-06-09 22:13 UTC, ejaronne commented
update README exec instructions to use main.tar.gz (not master)
update README "full heimdall server" url to point to heimdall2 repo not old heimdall

2022-06-10 02:17 UTC, ejaronne approved these changes

2022-06-10 13:12 UTC, karikarshivani commented
> microsoft-sql-server-2017-cis-1.2 relates to SI-10 (only for Mod/High) and SC-32 (non-mandatory). In planning in CFACTS, CMS ARS 3.1 non-mandatory controls are optional for ISSOs to adopt, and therefore may be something they still wish to include in their application's control set. Therefore, we don't exclude (make not applicable) a requirement based on non-mandatory NIST controls.

Good catch! Removed the caveat from cis-1.2
PR ready to be merged. Thanks!

2022-06-10 17:10 UTC, merged